name: Run ML Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install libs
      run: pip install torch torchvision pandas numpy scikit-fuzzy pillow

    - name: Run code
      run: python your_file.py

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: results.csv
