name: Run ML Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install libs
      run: pip install torch torchvision pandas numpy  pillow

    - name: Run code
      run: python code.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: results.csv
